spring:
  datasource:
    url: jdbc:mysql://192.168.0.2:3306/demo?characterEncoding=utf8
    username: jphs
    password: jphs%1234
  jpa:
    database: MYSQL
    show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNameingStrategy
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5Dialect
